(()=>{"use strict";
const V="2.1.0",K="tvtycoon-save-v2",days=["Sun","Mon","Tue","Wed","Thu","Fri","Sat"],times=["3 PM","4 PM","5 PM","6 PM","7 PM","8 PM","9 PM","10 PM"];
const starters=[["kids","Children's Club","Children","Local Production",350,34,"Families",60],["news","Local News","News","Local Production",500,39,"Adults",60],["variety","Local Variety Hour","Variety","Local Production",850,47,"Broad",60],["western","Western Film","Film","Acquired/Syndicated",650,45,"Men/Families",60],["wrestling","Studio Wrestling","Sports","Local Production",750,49,"Men",60],["film","Feature Film","Film","Acquired/Syndicated",900,52,"Broad",60],["music","Music & Dance","Music","Local Production",700,44,"Young Adults",60],["public","Community Forum","Public Affairs","Local Production",300,25,"Adults",60]];
const basePrograms=()=>starters.map(x=>({id:x[0],name:x[1],genre:x[2],source:x[3],cost:x[4],appeal:x[5],audience:x[6],length:x[7],custom:false}));
const C=[["NBC",68],["CBS",66],["ABC",51],["DuMont",48]];
function fresh(){let programs=basePrograms();return{week:1,date:"1950-01-01",cash:50000,rep:25,hours:"3 PM–11 PM",up:{earlier:false,camera:false},hist:[],last:null,programs,sched:Object.fromEntries(days.map((d,n)=>[d,times.map((t,i)=>({time:t,p:programs[(i+n%3)%programs.length].id}))]))}}
let s;try{s=JSON.parse(localStorage.getItem(K))||fresh()}catch(e){s=fresh()}
if(!s.programs)s.programs=basePrograms(); if(!s.up)s.up={earlier:false,camera:false};
let tab="Schedule",showAdd=false;
const p=id=>s.programs.find(x=>x.id===id)||s.programs[0],money=n=>"$"+Math.round(n).toLocaleString(),save=()=>localStorage.setItem(K,JSON.stringify(s));
function head(){let result=s.last?`Week ${s.last.w} complete • Rating ${s.last.r.toFixed(1)} • ${s.last.profit>=0?"+":""}${money(s.last.profit)}`:"No completed week yet";return `<header><div class="top"><div><h1>TV STATION TYCOON</h1><div class="muted">WXXX-TV • Week ${s.week} • ${s.date}</div></div><div class="stats"><span class="pill">${money(s.cash)}</span><span class="pill">Reputation ${s.rep}/100</span><span class="pill">${s.hours}</span></div></div><div class="global"><button id="sv">Save Game</button><button id="adv" class="primary">Advance Week</button><span class="last">${result}</span></div><nav>${["Station","Schedule","Programming","Ratings","Competition","Finances","Facilities","History"].map(x=>`<button data-tab="${x}" class="${tab===x?"active":""}">${x}</button>`).join("")}</nav></header>`}
function schedule(){return `<div class="panel"><h2>Weekly Schedule</h2><p class="muted">Every program in your library is available here. Edit each hour, then advance the week from the header.</p><div class="grid">${days.map(d=>`<div><h3>${d}</h3>${s.sched[d].map((x,i)=>`<div class="slot"><b>${x.time}</b><small>${p(x.p).genre} • ${money(p(x.p).cost)}</small><select data-d="${d}" data-i="${i}">${s.programs.map(q=>`<option value="${q.id}" ${q.id===x.p?"selected":""}>${q.name}</option>`).join("")}</select></div>`).join("")}</div>`).join("")}</div></div><div class="version">v${V}</div>`}
function programming(){return `<div class="panel"><div class="libraryHead"><div><h2>Program Library</h2><p class="muted">Programs are station assets. Add local productions or acquired/syndicated programming, then schedule them immediately.</p></div><button id="toggleAdd" class="primary">${showAdd?"Close":"Add Program"}</button></div>${showAdd?addForm():""}</div><div class="panel"><div class="cards">${s.programs.map(q=>`<div class="card"><h3>${q.name}</h3><div>${q.genre} • ${q.source}</div><p class="muted">${q.length} min • ${q.audience} • Appeal ${q.appeal}/100</p><b>${money(q.cost)} / airing</b>${q.custom?`<p class="version">Station-added program</p>`:""}</div>`).join("")}</div></div>`}
function addForm(){return `<div class="card"><h3>Add to Program Library</h3><div class="formgrid"><label>Program title<input id="pn" placeholder="e.g. Saturday Night Jamboree"></label><label>Genre<select id="pg">${["Variety","News","Drama","Comedy","Film","Sports","Music","Children","Public Affairs","Game Show","Other"].map(x=>`<option>${x}</option>`).join("")}</select></label><label>Source<select id="ps"><option>Local Production</option><option>Acquired/Syndicated</option></select></label><label>Length<select id="pl"><option value="30">30 minutes</option><option value="60" selected>60 minutes</option><option value="90">90 minutes</option><option value="120">120 minutes</option></select></label><label>Audience<select id="pa">${["Broad","Families","Adults","Young Adults","Men","Women","Children"].map(x=>`<option>${x}</option>`).join("")}</select></label><label>Cost per airing<input id="pc" type="number" min="50" value="500"></label><label>Expected appeal<input id="pp" type="number" min="1" max="100" value="40"></label><div class="wide"><button id="addProgram" class="primary">Add to Library</button> <span class="muted">Costs and appeal are player estimates for now; deeper production and contract rules will replace free-form values later.</span></div></div></div>`}
function comp(){return `<div class="panel"><h2>1950 Competition</h2><p class="muted">Historical baseline networks; weekly results are simulated around your decisions.</p><div class="cards">${C.map(x=>`<div class="card"><h3>${x[0]}</h3><b>Strength ${x[1]}</b></div>`).join("")}</div></div>`}
function ratings(){return `<div class="panel"><h2>Ratings</h2>${s.hist.length?`<table><tr><th>Week</th><th>Rating</th><th>Revenue</th><th>Profit</th></tr>${s.hist.slice().reverse().map(x=>`<tr><td>${x.w}</td><td>${x.r.toFixed(1)}</td><td>${money(x.rev)}</td><td>${money(x.profit)}</td></tr>`).join("")}</table>`:`<p class="muted">Advance a week for your first report.</p>`}</div>`}
function finances(){let a=s.hist.reduce((z,x)=>z+x.rev,0),b=s.hist.reduce((z,x)=>z+x.cost,0);return `<div class="panel"><h2>Finances</h2><p class="muted">This ledger will expand as advertising, payroll, contracts, production, debt, maintenance and other economic systems come online.</p><div class="cards"><div class="card">Cash<br><b>${money(s.cash)}</b></div><div class="card">Operating Revenue<br><b>${money(a)}</b></div><div class="card">Operating Costs<br><b>${money(b)}</b></div><div class="card">Net Operating<br><b>${money(a-b)}</b></div></div>${s.last?`<h3>Last Week</h3><table><tr><th>Revenue</th><th>Costs</th><th>Profit/Loss</th></tr><tr><td>${money(s.last.rev)}</td><td>${money(s.last.cost)}</td><td>${money(s.last.profit)}</td></tr></table>`:""}</div>`}
function facilities(){return `<div class="panel"><h2>Facilities & Technology</h2><p class="muted">Availability follows history; adoption is always your choice.</p><div class="cards"><div class="card"><h3>Earlier Sign-On</h3><button data-up="earlier" ${s.up.earlier?"disabled":""}>${s.up.earlier?"Purchased":"Buy $2,500"}</button></div><div class="card"><h3>Studio Camera Upgrade</h3><button data-up="camera" ${s.up.camera?"disabled":""}>${s.up.camera?"Purchased":"Buy $7,000"}</button></div></div></div>`}
function simple(){if(tab==="Station")return `<div class="panel"><h2>WXXX-TV</h2><p>Independent local station • ${s.hours}</p><p>Network affiliation: Independent. Affiliation will never be forced.</p></div>`;return `<div class="panel"><h2>Campaign History</h2><p>Reality supplies the baseline; your decisions create the timeline.</p>${s.hist.map(x=>`<p>Week ${x.w}: rating ${x.r.toFixed(1)}, profit ${money(x.profit)}</p>`).reverse().join("")||"<p>No completed weeks.</p>"}</div>`}
function view(){return tab==="Schedule"?schedule():tab==="Programming"?programming():tab==="Competition"?comp():tab==="Ratings"?ratings():tab==="Finances"?finances():tab==="Facilities"?facilities():simple()}
function render(){document.querySelector("#app").innerHTML=head()+`<main>${view()}</main>`;bind()}
function bind(){document.querySelectorAll("[data-tab]").forEach(b=>b.onclick=()=>{tab=b.dataset.tab;render()});document.querySelectorAll("select[data-d]").forEach(e=>e.onchange=()=>{s.sched[e.dataset.d][+e.dataset.i].p=e.value;save()});document.querySelector("#adv").onclick=advance;document.querySelector("#sv").onclick=e=>{save();e.target.textContent="Saved ✓";setTimeout(()=>{e.target.textContent="Save Game"},800)};document.querySelectorAll("[data-up]").forEach(b=>b.onclick=()=>buy(b.dataset.up));let t=document.querySelector("#toggleAdd");if(t)t.onclick=()=>{showAdd=!showAdd;render()};let a=document.querySelector("#addProgram");if(a)a.onclick=addProgram}
function addProgram(){let name=document.querySelector("#pn").value.trim();if(!name)return alert("Enter a program title.");let cost=Math.max(50,+document.querySelector("#pc").value||500),appeal=Math.min(100,Math.max(1,+document.querySelector("#pp").value||40));let id="custom-"+Date.now();s.programs.push({id,name,genre:document.querySelector("#pg").value,source:document.querySelector("#ps").value,length:+document.querySelector("#pl").value,audience:document.querySelector("#pa").value,cost,appeal,custom:true});save();showAdd=false;render()}
function buy(k){let n=k==="earlier"?2500:7000;if(s.cash<n)return alert("Not enough cash.");s.cash-=n;s.up[k]=true;if(k==="earlier")s.hours="2 PM–11 PM";else s.rep=Math.min(100,s.rep+5);save();render()}
function advance(){let a=days.flatMap(d=>s.sched[d]).map(x=>p(x.p)),cost=a.reduce((z,x)=>z+x.cost,4200),avg=a.reduce((z,x)=>z+x.appeal,0)/a.length,cs=C.reduce((z,x)=>z+x[1],0)/C.length,r=Math.max(1,avg*.17+s.rep*.055-cs*.035+(Math.random()*6-3)+(s.up.camera?1.2:0)),rev=Math.round(9000+r*2600+s.rep*95),profit=rev-cost,rec={w:s.week,r,rev,cost,profit};s.cash+=profit;s.last=rec;s.hist.push(rec);s.week++;let d=new Date(s.date+"T12:00:00");d.setDate(d.getDate()+7);s.date=d.toISOString().slice(0,10);if(profit>0)s.rep=Math.min(100,s.rep+1);save();render()}
window.addEventListener("error",e=>document.querySelector("#app").innerHTML=`<main><div class="panel"><h2>Startup error</h2><pre>${e.message}</pre></div></main>`);render();if("serviceWorker"in navigator)addEventListener("load",()=>navigator.serviceWorker.register("./sw.js").catch(console.warn));})();