(()=>{"use strict";
const V="2.3.3",K="tvtycoon-save-v2",DAYS=["Sun","Mon","Tue","Wed","Thu","Fri","Sat"],TIMES=["3 PM","4 PM","5 PM","6 PM","7 PM","8 PM","9 PM","10 PM"];
const STARTERS=[
["kids","Children's Club","Children","Local Production",350,34,"Families",60],["news","Local News","News","Local Production",500,39,"Adults",60],["variety","Local Variety Hour","Variety","Local Production",850,47,"Broad",60],["western","Western Film","Film","Acquired Library",650,45,"Men/Families",60],["wrestling","Studio Wrestling","Sports","Local Production",750,49,"Men",60],["film","Feature Film","Film","Acquired Library",900,52,"Broad",60],["music","Music & Dance","Music","Local Production",700,44,"Young Adults",60],["public","Community Forum","Public Affairs","Local Production",300,25,"Adults",60],["movie2","Feature Movie Presentation","Film","Acquired Library",1500,55,"Broad",120],["movie3","Epic Movie Presentation","Film","Acquired Library",2100,59,"Broad",180],["sports2","Live Sports Event (2 hr)","Sports","Event Rights",1800,57,"Broad",120],["sports3","Live Sports Event (3 hr)","Sports","Event Rights",2500,62,"Broad",180]];
const NETWORKS=[["NBC",68],["CBS",66],["ABC",51],["DuMont",48]];
const MARKET=[
{id:"hist-cisco",name:"The Cisco Kid",genre:"Western",source:"First-run Syndication",available:"1950-09-05",length:30,audience:"Families",cost:950,appeal:58,fee:6500,weeks:26,status:"HISTORICAL",economics:"ESTIMATED",note:"First-run syndicated from September 5, 1950."},
{id:"hist-wildbill",name:"The Adventures of Wild Bill Hickok",genre:"Western",source:"First-run Syndication",available:"1951-04-15",length:30,audience:"Families",cost:1000,appeal:59,fee:7000,weeks:26,status:"HISTORICAL",economics:"ESTIMATED",note:"Began in syndication April 15, 1951."},
{id:"hist-kitcarson",name:"The Adventures of Kit Carson",genre:"Western",source:"First-run Syndication",available:"1951-08-11",length:30,audience:"Families",cost:975,appeal:57,fee:6750,weeks:26,status:"HISTORICAL",economics:"ESTIMATED",note:"First-run syndicated beginning August 11, 1951."},
{id:"hist-boston",name:"Boston Blackie",genre:"Crime",source:"First-run Syndication",available:"1951-09-08",length:30,audience:"Adults",cost:1050,appeal:56,fee:7250,weeks:26,status:"HISTORICAL",economics:"ESTIMATED",note:"Syndicated detective series; September 1951 debut."}
];
const basePrograms=()=>STARTERS.map(x=>({id:x[0],name:x[1],genre:x[2],source:x[3],cost:x[4],appeal:x[5],audience:x[6],length:x[7],custom:false,career:{state:"active",origin:"BASELINE",seasons:1}}));
function fresh(){let programs=basePrograms();return{schema:4,week:1,date:"1950-01-01",cash:50000,rep:25,hours:"3 PM–11 PM",up:{earlier:false,camera:false},hist:[],last:null,programs,contracts:[],bids:[],divergences:[],notices:[],seenMarket:[],sched:Object.fromEntries(DAYS.map((d,n)=>[d,TIMES.map((t,i)=>({time:t,p:programs[(i+n%3)%programs.length].id}))]))}}
let s;try{s=JSON.parse(localStorage.getItem(K))||fresh()}catch(e){s=fresh()}
let tab="Schedule",showAdd=false;
function migrate(){s.schema=4;s.programs=s.programs||basePrograms();basePrograms().forEach(q=>{if(!s.programs.some(x=>x.id===q.id))s.programs.push(q)});s.contracts=s.contracts||[];s.bids=s.bids||[];s.divergences=s.divergences||[];s.notices=s.notices||[];s.seenMarket=s.seenMarket||[];s.up=s.up||{earlier:false,camera:false};s.hist=s.hist||[];s.programs.forEach(q=>{q.career=q.career||{state:"active",origin:q.id.startsWith("hist-")?"HISTORICAL":"BASELINE",seasons:1};if(q.id.startsWith("hist-")&&!s.contracts.some(c=>c.programId===q.id&&c.status==="active")){s.contracts.push({id:"mig-"+q.id,programId:q.id,startWeek:s.week,endWeek:s.week+25,termWeeks:26,fee:0,status:"active",season:1,source:"MIGRATED",renewalWindow:4})}});normalizeSchedule();save()}
const p=id=>s.programs.find(x=>x.id===id)||s.programs[0],money=n=>"$"+Math.round(n).toLocaleString(),save=()=>localStorage.setItem(K,JSON.stringify(s));
function hoursFor(q){return Math.max(1,Math.ceil((q.length||60)/60))}
function normalizeSchedule(){if(!s.sched)return;DAYS.forEach(d=>{let day=s.sched[d]||[];day.forEach(x=>{delete x.coveredBy});for(let i=0;i<day.length;i++){let q=p(day[i].p),span=hoursFor(q);if(span>1){for(let j=1;j<span&&i+j<day.length;j++)day[i+j].coveredBy=i;i+=span-1}}})}
function assignProgram(dayName,index,id){let day=s.sched[dayName],q=p(id),span=hoursFor(q);if(index+span>day.length)return alert(`${q.name} needs ${span} consecutive hours and will not fit before sign-off.`);day.forEach(x=>delete x.coveredBy);day[index].p=id;for(let j=1;j<span;j++)day[index+j].p=id;normalizeSchedule();save();render()}
function snapshotSchedule(){return Object.fromEntries(DAYS.map(d=>[d,s.sched[d].map((x,i)=>({time:x.time,p:x.p,coveredBy:x.coveredBy??null,name:p(x.p).name,genre:p(x.p).genre,length:p(x.p).length||60,cost:p(x.p).cost,start:x.coveredBy==null}))]))}
function timelineBoard(snapshot,editable=false){
  const cols=`78px repeat(7,minmax(145px,1fr))`, rows=`36px repeat(${TIMES.length},96px)`;
  let out=`<div class="scheduleScroll"><div class="scheduleBoard" style="grid-template-columns:${cols};grid-template-rows:${rows}"><div class="corner">TIME</div>`;
  DAYS.forEach((d,di)=>out+=`<div class="dayHead" style="grid-column:${di+2};grid-row:1">${d}</div>`);
  TIMES.forEach((t,ti)=>out+=`<div class="timeMark" style="grid-column:1;grid-row:${ti+2}"><b>${t}</b><span>${ti<TIMES.length-1?"30":""}</span></div>`);
  DAYS.forEach((d,di)=>TIMES.forEach((t,ti)=>out+=`<div class="timelineCell ${ti>=4?"primeCell":""}" style="grid-column:${di+2};grid-row:${ti+2}"></div>`));
  DAYS.forEach((d,di)=>{let day=snapshot[d]||[];day.forEach((x,i)=>{if(x.coveredBy!=null)return;let q=editable?p(x.p):x, span=Math.max(1,Math.ceil((q.length||60)/60)), end=Math.min(TIMES.length+2,i+2+span), genre=(q.genre||"Program").replace(/"/g,'&quot;'), name=(q.name||p(x.p).name).replace(/</g,'&lt;');out+=`<div class="programBlock genre-${genre.toLowerCase().replace(/[^a-z0-9]+/g,'-')}" style="grid-column:${di+2};grid-row:${i+2}/${end}"><div class="programName">${name}</div><div class="programMeta">${q.genre||"Program"} • ${q.length||60} min${editable?` • ${money(q.cost)}`:""}</div>${editable?`<select aria-label="${d} ${x.time}" data-d="${d}" data-i="${i}">${s.programs.filter(z=>z.career?.state!=="rights-expired").map(z=>`<option value="${z.id}" ${z.id===x.p?"selected":""}>${z.name}${(z.length||60)>60?` (${z.length}m)`:""}</option>`).join("")}</select>`:""}</div>`})});
  return out+`</div></div>`
}
function scheduleTable(snapshot){return timelineBoard(snapshot,false)}
migrate();
const activeContract=id=>s.contracts.find(c=>c.programId===id&&c.status==="active");
function head(){let result=s.last?`Week ${s.last.w} complete • Rating ${s.last.r.toFixed(1)} • ${s.last.profit>=0?"+":""}${money(s.last.profit)}`:"No completed week yet";let alerts=s.notices.filter(n=>!n.read).length;return `<header><div class="top"><div><h1>TV STATION TYCOON</h1><div class="muted">WXXX-TV • Week ${s.week} • ${s.date}</div></div><div class="stats"><span class="pill">${money(s.cash)}</span><span class="pill">Reputation ${s.rep}/100</span><span class="pill">${s.hours}</span>${alerts?`<span class="pill">${alerts} new</span>`:""}</div></div><div class="global"><button id="sv">Save Game</button><button id="adv" class="primary">Advance Week</button><span class="last">${result}</span></div><nav>${["Station","Schedule","Programming","Contracts","Ratings","Competition","Finances","Facilities","Timeline"].map(x=>`<button data-tab="${x}" class="${tab===x?"active":""}">${x}</button>`).join("")}</nav></header>`}
function schedule(){normalizeSchedule();return `<div class="panel"><div class="libraryHead"><div><h2>Weekly Schedule</h2><p class="muted">Time runs downward and each program physically spans its airtime. Scroll sideways on smaller screens.</p></div><span class="timelineKey">Prime time shaded • 1 row = 1 hour</span></div>${timelineBoard(s.sched,true)}</div><div class="version">v${V}</div>`}
function programming(){let owned=new Set(s.programs.map(x=>x.id)),available=MARKET.filter(x=>x.available<=s.date&&!owned.has(x.id)),upcoming=MARKET.filter(x=>x.available>s.date).sort((a,b)=>a.available.localeCompare(b.available));return `<div class="panel"><div class="libraryHead"><div><h2>Station Library</h2><p class="muted">Programs now have careers. Syndicated programs require active contracts; local productions can be renewed season by season.</p></div><button id="toggleAdd" class="primary">${showAdd?"Close":"Create Local Program"}</button></div>${showAdd?addForm():""}</div><div class="panel"><div class="cards">${s.programs.map(q=>{let c=activeContract(q.id);return `<div class="card"><h3>${q.name}</h3><div>${q.genre} • ${q.source}</div><p class="muted">${q.length||60} min • Appeal ${q.appeal}/100 • Season ${q.career?.seasons||1}</p><b>${money(q.cost)} / airing</b><p>${c?`Contract through Week ${c.endWeek} • ${Math.max(0,c.endWeek-s.week+1)} weeks left`:q.source==="First-run Syndication"?`<span class="bad">Rights expired</span>`:"Station-controlled"}</p></div>`}).join("")}</div></div><div class="panel"><h2>Historical Program Market</h2><p class="muted">History determines when an opportunity exists. Contract economics and bidding outcomes are simulated.</p>${available.length?`<div class="cards">${available.map(q=>`<div class="card"><h3>${q.name}</h3><p>${q.note}</p><p><b>${q.status}</b> availability • <b>${q.economics}</b> economics</p><p>Initial ${q.weeks}-week license: <b>${money(q.fee)}</b></p><button data-acquire="${q.id}" class="primary">Bid for Rights</button></div>`).join("")}</div>`:`<p>No new historical syndicated programs are currently available.</p>`}${upcoming.length?`<h3>Coming to Market</h3><table><tr><th>Program</th><th>Historical availability</th></tr>${upcoming.slice(0,6).map(q=>`<tr><td>${q.name}</td><td>${q.available}</td></tr>`).join("")}</table>`:""}</div>`}
function addForm(){return `<div class="card"><h3>Create Local Program</h3><div class="formgrid"><label>Program title<input id="pn" placeholder="e.g. Saturday Night Jamboree"></label><label>Genre<select id="pg">${["Variety","News","Drama","Comedy","Film","Sports","Music","Children","Public Affairs","Game Show","Other"].map(x=>`<option>${x}</option>`).join("")}</select></label><label>Length<select id="pl"><option value="30">30 minutes</option><option value="60" selected>60 minutes</option><option value="90">90 minutes</option><option value="120">2 hours</option><option value="180">3 hours</option></select></label><label>Audience<select id="pa">${["Broad","Families","Adults","Young Adults","Men","Women","Children"].map(x=>`<option>${x}</option>`).join("")}</select></label><label>Weekly production budget<input id="pc" type="number" min="100" value="600"></label><label>Creative ambition<select id="tier"><option value="-4">Shoestring</option><option value="0" selected>Standard</option><option value="6">Premium</option></select></label><div class="wide"><button id="addProgram" class="primary">Launch Season 1</button></div></div></div>`}
function contracts(){let active=s.contracts.filter(c=>c.status==="active"),soon=active.filter(c=>c.endWeek-s.week<=4),locals=s.programs.filter(q=>q.source==="Local Production"&&q.custom);return `<div class="panel"><h2>Contracts & Renewal Calendar</h2><p class="muted">Rights expire at the end of their term. During the final four weeks you can bid for another season. Competitors may contest desirable programming.</p>${active.length?`<table><tr><th>Program</th><th>Season</th><th>Expires</th><th>Status</th><th></th></tr>${active.map(c=>{let q=p(c.programId),left=c.endWeek-s.week+1;return `<tr><td>${q.name}</td><td>${c.season}</td><td>Week ${c.endWeek} (${left} wk)</td><td>${left<=4?"Renewal window":"Active"}</td><td>${left<=4?`<button data-renew="${c.id}">Bid to Renew</button>`:""}</td></tr>`}).join("")}</table>`:`<p>No active syndicated contracts.</p>`}</div><div class="panel"><h2>Local Production Seasons</h2><p class="muted">Local productions are station-controlled. A formal seasonal renewal cycle is now tracked for programs you create.</p>${locals.length?`<div class="cards">${locals.map(q=>`<div class="card"><h3>${q.name}</h3><p>Season ${q.career.seasons} • ${q.career.state}</p><button data-localrenew="${q.id}">Renew for Another Season</button></div>`).join("")}</div>`:`<p>Create a local program to manage its seasons here.</p>`}</div><div class="panel"><h2>Opportunity Desk</h2><p class="muted">Future historical cancellations, network releases and rescue opportunities will appear here. When history creates the opening, this campaign—not a script—will decide the outcome.</p></div>`}
function ratings(){let rows=s.hist.slice().reverse();return `<div class="panel"><h2>Ratings</h2><p class="muted">Tap a completed week to reopen the schedule that produced those results.</p>${rows.length?`<table><tr><th>Week</th><th>Rating</th><th>Revenue</th><th>Profit</th></tr>${rows.map(x=>`<tr class="ratingRow" data-week="${x.w}"><td><button class="weekLink" data-week="${x.w}">Week ${x.w}</button></td><td>${x.r.toFixed(1)}</td><td>${money(x.rev)}</td><td>${money(x.profit)}</td></tr>`).join("")}</table>`:`<p class="muted">Advance a week for your first report.</p>`}</div>${selectedHistoryWeek()!=null?historyDetail(selectedHistoryWeek()):""}`}
let historyWeek=null;
function selectedHistoryWeek(){if(historyWeek==null&&s.hist.length)historyWeek=s.hist[s.hist.length-1].w;return historyWeek}
function historyDetail(w){let rec=s.hist.find(x=>x.w===w);if(!rec)return "";if(!rec.schedule)return `<div class="panel"><h2>Week ${w} Schedule</h2><p class="muted">This week predates v2.3.2, so a schedule snapshot was not recorded. New completed weeks will retain their full schedules.</p></div>`;return `<div class="panel"><div class="libraryHead"><div><h2>Week ${w} Schedule</h2><p class="muted">Historical snapshot • Rating ${rec.r.toFixed(1)} • ${money(rec.profit)} profit/loss</p></div><button id="compareCurrent">${showCurrentCompare?"Hide Current":"Compare to Current"}</button></div>${scheduleTable(rec.schedule)}${showCurrentCompare?`<h3 class="compareTitle">Current Week ${s.week} Schedule</h3>${scheduleTable(snapshotSchedule())}`:""}</div>`}
let showCurrentCompare=false;
function competition(){return `<div class="panel"><h2>1950 Competition</h2><p class="muted">Historical entities, simulated weekly strength.</p><div class="cards">${NETWORKS.map(x=>`<div class="card"><h3>${x[0]}</h3><b>Strength ${x[1]}</b></div>`).join("")}</div></div>`}
function finances(){let a=s.hist.reduce((z,x)=>z+x.rev,0),b=s.hist.reduce((z,x)=>z+x.cost,0);return `<div class="panel"><h2>Finances</h2><div class="cards"><div class="card">Cash<br><b>${money(s.cash)}</b></div><div class="card">Operating Revenue<br><b>${money(a)}</b></div><div class="card">Operating Costs<br><b>${money(b)}</b></div><div class="card">Net Operating<br><b>${money(a-b)}</b></div></div>${s.last?`<h3>Last Week</h3><table><tr><th>Revenue</th><th>Costs</th><th>Profit/Loss</th></tr><tr><td>${money(s.last.rev)}</td><td>${money(s.last.cost)}</td><td>${money(s.last.profit)}</td></tr></table>`:""}</div>`}
function facilities(){return `<div class="panel"><h2>Facilities & Technology</h2><div class="cards"><div class="card"><h3>Earlier Sign-On</h3><button data-up="earlier" ${s.up.earlier?"disabled":""}>${s.up.earlier?"Purchased":"Buy $2,500"}</button></div><div class="card"><h3>Studio Camera Upgrade</h3><button data-up="camera" ${s.up.camera?"disabled":""}>${s.up.camera?"Purchased":"Buy $7,000"}</button></div></div></div>`}
function station(){return `<div class="panel"><h2>WXXX-TV</h2><p>Independent local station • ${s.hours}</p><p>Network affiliation: Independent. Affiliation will never be forced.</p></div><div class="panel"><h2>Campaign</h2><p class="muted">Start over from Sunday, January 1, 1950. This permanently replaces the current campaign.</p><button id="newGame" class="bad">New Game</button></div>`}
function timeline(){let rows=s.divergences.slice().reverse();return `<div class="panel"><h2>Our Timeline vs. History</h2><p class="muted">This ledger records moments where gameplay creates campaign canon. Historical opportunities remain reference points; divergent outcomes are never silently rewritten.</p>${rows.length?`<table><tr><th>Week</th><th>Program</th><th>Campaign outcome</th><th>Historical baseline</th></tr>${rows.map(x=>`<tr><td>${x.week}</td><td>${x.name}</td><td>${x.outcome}</td><td>${x.history}</td></tr>`).join("")}</table>`:`<p>No major divergences recorded yet.</p>`}</div><div class="panel"><h2>Recent Notices</h2>${s.notices.slice().reverse().slice(0,12).map(n=>`<p><b>Week ${n.week}:</b> ${n.text}</p>`).join("")||"<p>No notices yet.</p>"}</div>`}
function view(){return tab==="Station"?station():tab==="Schedule"?schedule():tab==="Programming"?programming():tab==="Contracts"?contracts():tab==="Ratings"?ratings():tab==="Competition"?competition():tab==="Finances"?finances():tab==="Facilities"?facilities():timeline()}
function render(){document.querySelector("#app").innerHTML=head()+`<main>${view()}</main>`;bind()}
function bind(){document.querySelectorAll("[data-tab]").forEach(b=>b.onclick=()=>{tab=b.dataset.tab;if(tab==="Timeline")s.notices.forEach(n=>n.read=true);save();render()});document.querySelectorAll("select[data-d]").forEach(e=>e.onchange=()=>assignProgram(e.dataset.d,+e.dataset.i,e.value));document.querySelectorAll("[data-week]").forEach(e=>e.onclick=()=>{historyWeek=+e.dataset.week;showCurrentCompare=false;render()});let cc=document.querySelector("#compareCurrent");if(cc)cc.onclick=()=>{showCurrentCompare=!showCurrentCompare;render()};document.querySelector("#adv").onclick=advance;document.querySelector("#sv").onclick=e=>{save();e.target.textContent="Saved ✓";setTimeout(()=>e.target.textContent="Save Game",800)};document.querySelectorAll("[data-up]").forEach(b=>b.onclick=()=>buy(b.dataset.up));document.querySelectorAll("[data-acquire]").forEach(b=>b.onclick=()=>bidAcquire(b.dataset.acquire));document.querySelectorAll("[data-renew]").forEach(b=>b.onclick=()=>renewBid(b.dataset.renew));document.querySelectorAll("[data-localrenew]").forEach(b=>b.onclick=()=>localRenew(b.dataset.localrenew));let t=document.querySelector("#toggleAdd");if(t)t.onclick=()=>{showAdd=!showAdd;render()};let a=document.querySelector("#addProgram");if(a)a.onclick=addProgram;let ng=document.querySelector("#newGame");if(ng)ng.onclick=newGame}
function addProgram(){let name=document.querySelector("#pn").value.trim();if(!name)return alert("Enter a program title.");let budget=Math.max(100,+document.querySelector("#pc").value||600),tier=+document.querySelector("#tier").value,id="local-"+Date.now(),appeal=Math.max(15,Math.min(75,30+Math.log10(budget)*5+tier));s.programs.push({id,name,genre:document.querySelector("#pg").value,source:"Local Production",length:+document.querySelector("#pl").value,audience:document.querySelector("#pa").value,cost:budget,appeal,custom:true,career:{state:"active",origin:"PLAYER",seasons:1}});s.divergences.push({week:s.week,name,outcome:"WXXX launched an original local production.",history:"No fixed historical counterpart."});save();showAdd=false;render()}
function bidAcquire(id){let q=MARKET.find(x=>x.id===id);if(!q)return;let suggested=q.fee,bid=+prompt(`Submit a rights bid for ${q.name}.\nSuggested package: ${money(suggested)} for ${q.weeks} weeks.\nEnter your bid:`,suggested);if(!bid||bid<1)return;if(s.cash<bid)return alert("You do not have enough cash for that bid.");let pressure=.82+Math.random()*.38,threshold=q.fee*pressure;let won=bid>=threshold;if(!won){s.notices.push({week:s.week,text:`Your ${money(bid)} bid for ${q.name} was rejected. Another buyer valued the package more highly.`,read:false});save();return render()}s.cash-=bid;s.programs.push({...q,custom:false,career:{state:"active",origin:"HISTORICAL",seasons:1}});s.contracts.push({id:"ctr-"+Date.now(),programId:q.id,startWeek:s.week,endWeek:s.week+q.weeks-1,termWeeks:q.weeks,fee:bid,status:"active",season:1,source:"BID",renewalWindow:4});s.notices.push({week:s.week,text:`WXXX won ${q.weeks}-week rights to ${q.name} for ${money(bid)}.`,read:false});save();render()}
function renewBid(cid){let c=s.contracts.find(x=>x.id===cid),q=p(c.programId),base=(MARKET.find(x=>x.id===q.id)?.fee||c.fee||5000)*(1+Math.max(0,q.appeal-50)/100),bid=+prompt(`Renew ${q.name} for another ${c.termWeeks}-week season.\nDistributor estimate: ${money(base)}.\nEnter your bid:`,Math.round(base));if(!bid||bid<1)return;if(s.cash<bid)return alert("Not enough cash.");let threshold=base*(.85+Math.random()*.35);if(bid<threshold){s.notices.push({week:s.week,text:`Renewal bid for ${q.name} was rejected. Rights remain active only through Week ${c.endWeek}.`,read:false});save();return render()}s.cash-=bid;c.endWeek+=c.termWeeks;c.season++;c.fee=bid;q.career.seasons=c.season;s.divergences.push({week:s.week,name:q.name,outcome:`WXXX renewed the series for Season ${c.season}.`,history:"Historical availability created the opportunity; campaign contract outcome is simulated."});s.notices.push({week:s.week,text:`Renewal secured: ${q.name}, Season ${c.season}, through Week ${c.endWeek}.`,read:false});save();render()}
function localRenew(id){let q=p(id),fee=Math.round(q.cost*8);if(!confirm(`Renew ${q.name} for another local-production season? Development commitment: ${money(fee)}.`))return;if(s.cash<fee)return alert("Not enough cash.");s.cash-=fee;q.career.seasons++;q.appeal=Math.min(90,q.appeal+Math.random()*4);s.divergences.push({week:s.week,name:q.name,outcome:`WXXX renewed its local production for Season ${q.career.seasons}.`,history:"Player-created alternate-history program."});save();render()}
function expireContracts(){s.contracts.filter(c=>c.status==="active"&&c.endWeek<s.week).forEach(c=>{c.status="expired";let q=p(c.programId);q.career.state="rights-expired";s.notices.push({week:s.week,text:`Rights expired for ${q.name}. It has been removed from active scheduling.`,read:false});let fallback=s.programs.find(x=>x.career?.state!=="rights-expired")?.id;s.sched&&Object.values(s.sched).flat().forEach(slot=>{if(slot.p===q.id)slot.p=fallback})})}
function marketNotices(){MARKET.filter(q=>q.available<=s.date&&!s.seenMarket.includes(q.id)).forEach(q=>{s.seenMarket.push(q.id);s.notices.push({week:s.week,text:`New historical market opportunity: ${q.name} is now available for rights bidding.`,read:false})})}
function buy(k){let n=k==="earlier"?2500:7000;if(s.cash<n)return alert("Not enough cash.");s.cash-=n;s.up[k]=true;if(k==="earlier")s.hours="2 PM–11 PM";else s.rep=Math.min(100,s.rep+5);save();render()}
function newGame(){if(!confirm("Start a new game? This will permanently erase the current campaign and return to January 1, 1950."))return;if(!confirm("Are you sure? Your timeline, contracts, finances, ratings and program library will be replaced."))return;s=fresh();save();tab="Station";showAdd=false;render()}
function advance(){normalizeSchedule();let snapshot=snapshotSchedule(),aired=DAYS.flatMap(d=>s.sched[d].filter(x=>x.coveredBy==null)).map(x=>p(x.p)),weighted=DAYS.flatMap(d=>s.sched[d].filter(x=>x.coveredBy==null)).map(x=>p(x.p)).flatMap(q=>Array(hoursFor(q)).fill(q)),cost=4200+aired.reduce((z,x)=>z+x.cost,0),avg=weighted.reduce((z,x)=>z+x.appeal,0)/Math.max(1,weighted.length),cs=NETWORKS.reduce((z,x)=>z+x[1],0)/NETWORKS.length,r=Math.max(1,avg*.17+s.rep*.055-cs*.035+(Math.random()*6-3)+(s.up.camera?1.2:0)),rev=Math.round(9000+r*2600+s.rep*95),profit=rev-cost,rec={w:s.week,date:s.date,r,rev,cost,profit,schedule:snapshot};s.cash+=profit;s.last=rec;s.hist.push(rec);historyWeek=rec.w;s.week++;let d=new Date(s.date+"T12:00:00");d.setDate(d.getDate()+7);s.date=d.toISOString().slice(0,10);if(profit>0)s.rep=Math.min(100,s.rep+1);expireContracts();marketNotices();save();render()}
window.addEventListener("error",e=>document.querySelector("#app").innerHTML=`<main><div class="panel"><h2>Startup error</h2><pre>${e.message}</pre></div></main>`);marketNotices();render();if("serviceWorker"in navigator)addEventListener("load",()=>navigator.serviceWorker.register("./sw.js").catch(console.warn));})();
